export const googleTtsVoices = [
  { id: 'Zephyr', name: 'Zephyr (Bright)' }, 
  { id: 'Puck', name: 'Puck (Upbeat)' }, 
  { id: 'Charon', name: 'Charon (Informative)' },
  { id: 'Kore', name: 'Kore (Firm)' }, 
  { id: 'Fenrir', name: 'Fenrir (Excitable)' }, 
  { id: 'Leda', name: 'Leda (Youthful)' },
  { id: 'Orus', name: 'Orus (Firm)' }, 
  { id: 'Aoede', name: 'Aoede (Breezy)' }, 
  { id: 'Callirhoe', name: 'Callirhoe (Easy-going)' },
  { id: 'Autonoe', name: 'Autonoe (Bright)' }, 
  { id: 'Enceladus', name: 'Enceladus (Breathy)' }, 
  { id: 'Iapetus', name: 'Iapetus (Clear)' },
  { id: 'Umbriel', name: 'Umbriel (Easy-going)' }, 
  { id: 'Algieba', name: 'Algieba (Smooth)' }, 
  { id: 'Despina', name: 'Despina (Smooth)' },
  { id: 'Erinome', name: 'Erinome (Clear)' }, 
  { id: 'Algenib', name: 'Algenib (Gravelly)' }, 
  { id: 'Rasalgethi', name: 'Rasalgethi (Informative)' },
  { id: 'Laomedeia', name: 'Laomedeia (Upbeat)' }, 
  { id: 'Achernar', name: 'Achernar (Soft)' }, 
  { id: 'Alnilam', name: 'Alnilam (Firm)' },
  { id: 'Schedar', name: 'Schedar (Even)' }, 
  { id: 'Gacrux', name: 'Gacrux (Mature)' }, 
  { id: 'Pulcherrima', name: 'Pulcherrima (Forward)' },
  { id: 'Achird', name: 'Achird (Friendly)' }, 
  { id: 'Zubenelgenubi', name: 'Zubenelgenubi (Casual)' }, 
  { id: 'Vindemiatrix', name: 'Vindemiatrix (Gentle)' },
  { id: 'Sadachbia', name: 'Sadachbia (Lively)' }, 
  { id: 'Sadaltager', name: 'Sadaltager (Knowledgeable)' }, 
  { id: 'Sulafar', name: 'Sulafar (Warm)' }
];

export const googleTtsApiModels = [
  { id: 'gemini-2.5-flash-preview-tts', name: 'Gemini 2.5 Flash TTS' },
  { id: 'gemini-2.5-pro-preview-tts', name: 'Gemini 2.5 Pro TTS' }
];

export const googleTtsLanguages = [
  { id: 'ar-EG', name: 'Arabic (Egyptian)' }, 
  { id: 'de-DE', name: 'German (Germany)' },
  { id: 'en-US', name: 'English (US)' }, 
  { id: 'es-US', name: 'Spanish (US)' },
  { id: 'fr-FR', name: 'French (France)' }, 
  { id: 'hi-IN', name: 'Hindi (India)' },
  { id: 'id-ID', name: 'Indonesian (Indonesia)' }, 
  { id: 'it-IT', name: 'Italian (Italy)' },
  { id: 'ja-JP', name: 'Japanese (Japan)' }, 
  { id: 'ko-KR', name: 'Korean (Korea)' },
  { id: 'pt-BR', name: 'Portuguese (Brazil)' }, 
  { id: 'ru-RU', name: 'Russian (Russia)' },
  { id: 'nl-NL', name: 'Dutch (Netherlands)' }, 
  { id: 'pl-PL', name: 'Polish (Poland)' },
  { id: 'th-TH', name: 'Thai (Thailand)' }, 
  { id: 'tr-TR', name: 'Turkish (Turkey)' },
  { id: 'vi-VN', name: 'Vietnamese (Vietnam)' }, 
  { id: 'ro-RO', name: 'Romanian (Romania)' },
  { id: 'uk-UA', name: 'Ukrainian (Ukraine)' }, 
  { id: 'bn-BD', name: 'Bengali (Bangladesh)' },
  { id: 'en-IN', name: 'English (India)' }, 
  { id: 'mr-IN', name: 'Marathi (India)' },
  { id: 'ta-IN', name: 'Tamil (India)' }, 
  { id: 'te-IN', name: 'Telugu (India)' }
];
